name: Send a HTTP Request when new RSS item is detected
on:
  rss:
    url: 
      - https://jsomers.net/blog/feed
      - https://unbug.github.io/feed.xml
      - https://draveness.me/feed.xml
      - https://tech.meituan.com/feed
      - https://martinfowler.com/feed.atom
      - https://web.dev/feed.xml
      - https://hypercritical.co/feeds/main
      - https://feeds.feedburner.com/marginalrevolution/feed
      - https://wangyurui.com/feed.xml
      - http://www.newyorker.com/services/rss/feeds/everything.xml
jobs:
  request:
    name: Request
    runs-on: ubuntu-latest
    steps:
      - name: Make a HTTP Request      
        uses: actionsflow/axios@main
        with:
          url: ${{secrets.CUBOXAPI}}
          method: POST
          body: |
            {
              "type":"url", 
              "title": "${{ on.rss.outputs.title }}",
              "content":"${{ on.rss.outputs.link }}",
              "folder":"RSS"
            }
