name: Send a HTTP Request when new RSS item is detected
on:
  rss:
    url: 
      - https://jsomers.net/blog/feed
      - https://tomhazledine.com/feed.xml
      - https://unbug.github.io/feed.xml
      - https://draveness.me/feed.xml
      - https://tech.meituan.com/feed
      - https://martinfowler.com/feed.atom
      - https://web.dev/feed.xml
      - https://hypercritical.co/feeds/main
      - https://feeds.feedburner.com/marginalrevolution/feed
      - https://wangyurui.com/feed.xml
      - https://feeds.feedburner.com/martinkl
      - https://spring.io/blog.atom
      - https://feeds.feedblitz.com/baeldung
      - https://blog.t9t.io/atom.xml
      - https://feeds.feedburner.com/ruanyifeng
      - https://news.ycombinator.com/rss
      - https://portswigger.net/research/rss
      - https://googleprojectzero.blogspot.com/feeds/posts/default
      - https://kevinlynagh.com/feed.xml
      - https://www.microsoft.com/en-us/research/feed/
      - https://www.kawabangga.com/feed
      - https://stephango.com/feed.xml
      - https://thesephist.com/index.xml
      - https://blog.brachiosoft.com/index.xml
      
jobs:
  request:
    name: Request
    runs-on: ubuntu-latest
    steps:
      - name: Make a HTTP Request      
        uses: actionsflow/axios@main
        with:
          url: ${{secrets.CUBOXAPI}}
          method: POST
          body: |
            {
              "type":"url", 
              "title": "${{ on.rss.outputs.title }}",
              "content":"${{ on.rss.outputs.link }}",
              "folder":"RSS"
            }
